Noviembre.Web/Controllers/ConsultaController.cs
using Noviembre.Core.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Noviembre.Web.Controllers
{
    public class ConsultaController : Controller
    {
        // GET: Consulta
        public ActionResult Index()
        {
            List<Consulta> consultas = Consulta.GetAll();
            return View(consultas);
        }

        public ActionResult Eliminar(int id)
        {
            Consulta.Eliminar(id);
            return RedirectToAction("Index");

        }
    }
}

Noviembre.Web/Controllers/ConsultorioController.cs
using Noviembre.Core.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Noviembre.Web.Controllers
{
    public class ConsultorioController : Controller
    {
        // GET: Consultorio
        public ActionResult Index()
        {
            List<Consultorio> consultorios = Consultorio.GetAll();
            return View(consultorios);
        }
        public ActionResult Registro(int id)
        {
            Consultorio consultorio = Consultorio.GetById(id);
            return View(consultorio);
        }
        public ActionResult Guardar(int id, int numeroExterior, int idDoctor)
        {
            Consultorio.Guardar(id, numeroExterior, idDoctor);
            return RedirectToAction("Index");

        }

        public ActionResult Eliminar(int id)
        {
            Consultorio.Eliminar(id);
            return RedirectToAction("Index");

        }
    }
}

Noviembre.Web/Controllers/DoctorController.cs
using Noviembre.Core.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Noviembre.Web.Controllers
{
    public class DoctorController : Controller
    {
        // GET: Doctor
        public ActionResult Index()
        {
            List<Doctor> doctores = Doctor.GetAll();
            return View(doctores);
        }

        public ActionResult Registro(int id)
        {
            Doctor doctores = Doctor.GetById(id);
            return View(doctores);
        }
        public ActionResult Guardar(int id, string nombre, string apellido, string RFC, string cedulaProfecional, string email, string especialidad)
        {
            Doctor.Guardar(id, nombre, apellido, RFC, cedulaProfecional, email, especialidad);
            return RedirectToAction("Index"); 

        }

        public ActionResult Eliminar(int id)
        {
            Doctor.Eliminar(id);
            return RedirectToAction("Index");

        }
    }
}

Noviembre.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Noviembre.Web.Controllers
{
    public class HomeController : Controller
    {

        //acciones de controlador
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Bienvenido() { 
        
            return View();

        }


        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Noviembre.Web/Controllers/PacienteController.cs
using Noviembre.Core.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Noviembre.Web.Controllers
{
    public class PacienteController : Controller
    {
        // GET: Paciente
        public ActionResult Index()
        {
            List<Paciente> pacientes = Paciente.GetAll();
            return View(pacientes);

        }

        public ActionResult Registro(int id)
        {
            Paciente pacientes = Paciente.GetById(id);
            return View(pacientes);
        }

        public ActionResult Guardar(int id, string nombre, string apellido, string nss, string curp, string email)
        {
            Paciente.Guardar(id, nombre, apellido, nss, curp, email);
            return RedirectToAction("Index");


        }

        public ActionResult Eliminar(int id)
        {
            Paciente.Eliminar(id);
            return RedirectToAction("Index");

        }
    }
}

Noviembre.Web/Views/Consulta/Index.cshtml
<!-- Page Content -->
@using Noviembre.Core.Entidades
@model List<Consulta>

<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Consultas</h1>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-body">

                        

                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>Fecha</th>
                                        <th>Nombre del Doctor</th>
                                        <th>Apellido del Doctor</th>
                                        <th>Consultorio</th>
                                        <th>Nombre del Paciente</th>
                                        <th>Apellido del Paciente</th>


                                    </tr>
                                </thead>

                                <tbody>
                                    @foreach (Consulta e in Model)
                                    {
                                        <tr>
                                            <td>
                                                @e.Fecha
                                            </td>
                                            <td>
                                                @e.Doctor.Nombre
                                            </td>
                                            <td>
                                                @e.Doctor.Apellido
                                            </td>
                                            <td>
                                                @e.Consultorio.NumeroExterior
                                            </td>
                                            <td>
                                                @e.Paciente.Nombre
                                            </td>
                                            <td>
                                                @e.Paciente.apellido
                                            </td>
                                            <td>

                                                <a onclick="eliminar(@e.Id)" class="btn fa fa-trash btn-danger btn-circle"></a>

                                            </td>
                                        </tr>



                                    }

                                </tbody>
                            </table>
                           
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>
</div>

<script src="~/Content/js/Undeath/consulta.js"></script>

Noviembre.Web/Views/Consultorio/Index.cshtml
<!-- Page Content -->
@using Noviembre.Core.Entidades
@model List<Consultorio>

<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Consultorios</h1>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-body">

                        

                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>Número De Consultorio</th>
                                        <th>Nombre</th>
                                        <th>Apellido</th>
                                        <th>Especialidad</th>


                                    </tr>
                                </thead>

                                <tbody>
                                    @foreach (Consultorio e in Model)
                                    {
                                        <tr>
                                            <td>
                                                @e.NumeroExterior
                                            </td>
                                            <td>
                                                @e.Doctor.Nombre
                                            </td>
                                            <td>
                                                @e.Doctor.Apellido
                                            </td>
                                            <td>
                                                @e.Doctor.Especialidad
                                            </td>
                                            <td>
                                                <a href="@Url.Action("Registro", "Consultorio", new { @id = e.Id })" class="btn btn-primary btn-circle"> <i class="fa fa-pencil"></i> Editar</a>
                                                <a onclick="eliminar(@e.Id)" class="btn fa fa-trash btn-danger btn-circle"></a>

                                            </td>
                                        </tr>



                                    }

                                </tbody>
                            </table>
                            <a href="@Url.Action("Registro","Consultorio", new {id =0 })" class="btn btn-primary">Agregar nuevo</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>
</div>

<script src="~/Content/js/Undeath/consultorio.js"></script>

Noviembre.Web/Views/Consultorio/Registro.cshtml
@using Noviembre.Core.Entidades
@model Consultorio


<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Registro de Consultorio</h1>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-body">

                        <form action="@Url.Action("Guardar", "Consultorio")">
                            <input type="hidden" class="form-control" name="id" value="@Model.Id">

                            <div class="form-group">
                                <label>Número de Consultorio:</label>
                                <input class="form-control" name="numeroExterior" value="@if (Model.Id != 0) { @Model.NumeroExterior}" />
                                <label>Número de Doctor:</label>
                                <input class="form-control" name="idDoctor" value="@if (Model.Id != 0) { @Model.Doctor.Id}" />



                            </div>

                            <button class="btn btn-success" type="submit">Guardar</button>

                        </form>

                    </div>
                        
                </div>
            </div>
        </div>


    </div>
</div>

Noviembre.Web/Views/Doctor/Index.cshtml
<!-- Page Content -->
@using Noviembre.Core.Entidades
@model List<Doctor>

<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Doctores</h1>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-body">

                        

                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>Nombre</th>
                                        <th>Apellido</th>
                                        <th>Especialidad</th>


                                    </tr>
                                </thead>

                                <tbody>
                                    @foreach (Doctor e in Model)
                                    {
                                        <tr>
                                            <td>
                                                @e.Nombre
                                            </td>
                                            <td>
                                                @e.Apellido
                                            </td>
                                            <td>
                                                @e.Especialidad
                                            </td>
                                            <td>
                                                <a href="@Url.Action("Registro", "Doctor", new { @id = e.Id })" class="btn btn-primary btn-circle"> <i class="fa fa-pencil"></i> Editar</a>
                                                <a onclick="eliminar(@e.Id)" class="btn fa fa-trash btn-danger btn-circle"></a>

                                            </td>
                                        </tr>



                                    }

                                </tbody>
                            </table>
                            <a href="@Url.Action("Registro","Doctor", new {id =0 })" class="btn btn-primary">Agregar nuevo</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>
</div>


<script src="~/Content/js/Undeath/doctor.js"></script>

Noviembre.Web/Views/Doctor/Registro.cshtml
@using Noviembre.Core.Entidades
@model Doctor

<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Registro de doctores</h1>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-body">

                        <form action="@Url.Action("Guardar", "Doctor")">
                            <input type="hidden" class="form-control" name="id" value="@Model.Id">

                            <div class="form-group">
                                <label>Nombre del Doctor:</label>
                                <input class="form-control" name="nombre" value="@if (Model.Id != 0) { @Model.Nombre}" />
                                <label>Apellidos del Doctor:</label>
                                <input class="form-control" name="apellido" value="@if (Model.Id != 0) { @Model.Apellido}" />
                                <label>RFC del Doctor:</label>
                                <input class="form-control" name="RFC" value="@if (Model.Id != 0) { @Model.RFC}" />
                                <label>Cedula profecional del Doctor:</label>
                                <input class="form-control" name="cedulaProfecional" value="@if (Model.Id != 0) { @Model.CedulaProfecional}" />
                                <label>Correo electronico del Doctor:</label>
                                <input class="form-control" name="email" value="@if (Model.Id != 0) { @Model.Email}" />
                                <label>Especialidad del Doctor:</label>
                                <input class="form-control" name="especialidad" value="@if (Model.Id != 0) { @Model.Especialidad}" />


                            </div>

                            <button class="btn btn-success" type="submit">Guardar</button>

                        </form>

                    </div>
                </div>
            </div>
        </div>


    </div>
</div>

Noviembre.Web/Views/Home/Bienvenido.cshtml
<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Bienvenido otra vez</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->

Noviembre.Web/Views/Home/Index.cshtml
<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Bienvenido al sistema de administracion de IMSS (Igual que las oficinas no hay citas.)</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->

Noviembre.Web/Views/Paciente/Index.cshtml
<!-- Page Content -->
@using Noviembre.Core.Entidades
@model List<Paciente>

<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Pacientes</h1>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-body">

                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>Nombre</th>
                                        <th>Apellido</th>
                                        <th>Número de Seguro Social</th>
                                        <th>Curp</th>
                                        <th>Email</th>
                                        <th>Acciones</th>

                                    </tr>
                                </thead>

                                <tbody>
                                    @foreach (Paciente e in Model)
                                    {
                                        <tr>
                                            <td>
                                                @e.Nombre
                                            </td>
                                            <td>
                                                @e.apellido
                                            </td>
                                            <td>
                                                @e.nss
                                            </td>
                                            <td>
                                                @e.curp
                                            </td>
                                            <td>
                                                @e.email
                                            </td>

                                            <td>
                                                <a href="@Url.Action("Registro", "Paciente", new { @id = e.Id })" class="btn btn-primary btn-circle"> <i class="fa fa-pencil"></i> Editar</a>
                                                <a onclick="eliminar(@e.Id)" class="btn fa fa-trash btn-danger btn-circle"></a>

                                            </td>
                                        </tr>
                                    }

                                </tbody>
                            </table>
                            <a href="@Url.Action("Registro","Paciente", new {id =0 })" class="btn btn-primary">Agregar nuevo</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>
</div>

<script src="~/Content/js/Undeath/paciente.js"></script>

Noviembre.Web/Views/Paciente/Registro.cshtml
@using Noviembre.Core.Entidades
@model Paciente

<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Registro de paciente</h1>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-body">

                        <form action="@Url.Action("Guardar", "Paciente")">
                            <input type="hidden" class="form-control" name="id" value="@Model.Id">

                            <div class="form-group">
                                <label>Nombre del paciente:</label>
                                <input class="form-control" name="nombre" value="@if (Model.Id != 0) { @Model.Nombre}" />

                                <label>Apellidos del paciente:</label>
                                <input class="form-control" name="apellido" value="@if (Model.Id != 0) { @Model.apellido}" />

                                <label>Numero de seguro social del paciente:</label>
                                <input class="form-control" name="nss" value="@if (Model.Id != 0) { @Model.nss}" />

                                <label>Curp paciente:</label>
                                <input class="form-control" name="curp" value="@if (Model.Id != 0) { @Model.curp}" />

                                <label>Email del paciente:</label>
                                <input class="form-control" name="email" value="@if (Model.Id != 0) { @Model.email}" />


                            </div>

                            <button class="btn btn-success" type="submit">Guardar</button>

                        </form>

                    </div>
                </div>
            </div>
        </div>


    </div>
</div>

Noviembre.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Startmin - Bootstrap Admin Theme</title>

    <!-- Bootstrap Core CSS -->
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="~/Content/css/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="~/Content/css/startmin.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="~/Content/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="navbar-header">
                
                <a class="navbar-brand" href="index.html">IMSS</a>
            </div>

            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <ul class="nav navbar-nav navbar-left navbar-top-links">
                <li><a href="#"><i class="fa fa-home fa-fw"></i> Website</a></li>
            </ul>

            <ul class="nav navbar-right navbar-top-links">
                <li class="dropdown navbar-inverse">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-bell fa-fw"></i> <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu dropdown-alerts">
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-comment fa-fw"></i> New Comment
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                    <span class="pull-right text-muted small">12 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-envelope fa-fw"></i> Message Sent
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-tasks fa-fw"></i> New Task
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="text-center" href="#">
                                <strong>See All Alerts</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                </li>
                
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-primary" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                            <!-- /input-group -->
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Home")"><i class="fa fa-th"></i> Inicio</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Paciente")"><i class="fa fa-users"></i> Pacientes</a>
                        </li>

                        <li>
                            <a href="@Url.Action("Index", "Consultorio")"><i class="fa fa-picture-o"></i> Consultorios</a>
                        </li>

                        <li>
                            <a href="@Url.Action("Index", "Doctor")"><i class="fa fa-newspaper-o"></i> Doctores</a>
                        </li>

                        <li>
                            <a href="@Url.Action("Index", "Consulta")"><i class="fa fa-file-text"></i> Nueva Cita</a>
                        </li>

                            

                       


                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>


        @RenderBody()


    </div>
    <!-- /#wrapper -->
    <!-- jQuery -->
    <script src="~/Content/js/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="~/Content/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="~/Content/js/metisMenu.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="~/Content/js/startmin.js"></script>

</body>
</html>